fastq_directory:
  class: Directory
  location: /storage/scontaldo/fungi/test 
index_hg38:
  class: File
  path: /home/scontaldo/variantCalling/hg38-20221027/indexGenome/hg38.fa
threads: 30 
db_path:
  class: File
  path: /storage/scontaldo/fungi/krakenDB/Virus/hash.k2d
index_chm13:
  class: File
  path: /home/scontaldo/variantCalling/hg38-20221027/indexGenome/hg38.fa
meta_path:
  class: Directory
  location: /storage/scontaldo/metaphlan 
chocophlan_DB:
  class: Directory
  location: /storage/scontaldo/chocophlan
uniref_DB:
  class: Directory
  location: /storage/scontaldo/uniref
