fastq_directory:
  class: Directory
  location: ../prova 
indexes:
  - class: File
    path: /data/ref/hg38/hg38.fa
    secondaryFiles:
      - class: File
        path: /data/ref/hg38/hg38.fa.amb
      - class: File
        path: /data/ref/hg38/hg38.fa.ann
      - class: File
        path: /data/ref/hg38/hg38.fa.bwt
      - class: File
        path: /data/ref/hg38/hg38.fa.fai
      - class: File
        path: /data/ref/hg38/hg38.fa.pac
      - class: File
        path: /data/ref/hg38/hg38.fa.sa
  - class: File
    path: /data/ref/chm13/chm13v2.0.fa
    secondaryFiles:
      - class: File
        path: /data/ref/chm13/chm13v2.0.fa.amb
      - class: File
        path: /data/ref/chm13/chm13v2.0.fa.ann
      - class: File
        path: /data/ref/chm13/chm13v2.0.fa.bwt
      - class: File
        path: /data/ref/chm13/chm13v2.0.fa.pac
      - class: File
        path: /data/ref/chm13/chm13v2.0.fa.sa
threads: 36
kraken_path:
  class: File
  path: /data/ref/kraken/hash.k2d
meta_path:
  class: Directory
  location: /data/ref/metaphlan 
chocophlan_DB:
  class: Directory
  location: /data/ref/chocophlan
uniref_DB:
  class: Directory
  location: /data/ref/uniref
paired_end: true
algorithm: both
db_bracken: 
  class: File
  path: /data/ref/kraken/database150mers.kmer_distrib